lib/timesheet_web/router.ex
defmodule TimesheetWeb.Router do
  use TimesheetWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TimesheetWeb.Plugs.FetchCurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TimesheetWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/sheets",SheetController,
       only: [:new, :create, :index, :show, :update, :edit] 
    resources "/users", UserController,
       only: [:new, :create, :show, :index]
    resources "/tasks", TaskController,
	only: [:new, :create]
    resources "/sessions", SessionController, 
      only: [:new, :create, :delete], singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", TimesheetWeb do
  #   pipe_through :api
  # end
end

lib/timesheet_web/views/layout_view.ex
defmodule TimesheetWeb.LayoutView do
  use TimesheetWeb, :view
end

lib/timesheet_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Timesheet · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
    <body>
    <div class="container">
      <nav class="navbar navbar-expand-sm navbar-light bg-white">
        <div class="col-4">
	  <span class="navbar-brand">Timesheet</span>
        </div>
        <div class="col-4">
	<%= if @current_user do %>
          <%= if !@current_user.is_manager do %>
            <%= link("NewTimesheet", to: Routes.sheet_path(@conn, :new)) %> 
          <% end %>
	<% end %>
        </div>
        <div class="col-4 text-light">
          <%= if @current_user do %>
	  User: <%= link(@current_user.name,
              to: Routes.user_path(@conn, :show, @current_user)) %>
            (<%= link("Logout", to: Routes.session_path(@conn, :delete),
              method: :delete) %>)
          <% else %>
            <%= link("Login", to: Routes.session_path(@conn, :new)) %> |
	    <%= link("Register", to: Routes.user_path(@conn, :new)) %>
          <% end %>
        </div>
      </nav>

      <div class="row">
        <div class="col-12">
          <%= if get_flash(@conn, :info) do %>
            <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <% end %>
          <%= if get_flash(@conn, :error) do %>
            <p class="alert alert-danger" role="alert">
              <%= get_flash(@conn, :error) %>
            </p>
          <% end %>
        </div>
      </div>

      <%= render @view_module, @view_template, assigns %>
    </div>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>